# Commands to start on workspace startup
tasks:
  - init: npm install -g live-server
    command: live-server --port 8080
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview
