# Commands to start on workspace startup
tasks:
  - before: npm install -g live-server
    command: mkdir -p cmbuild && live-server --port=8080 cmbuild
  - before: . /home/gitpod/emsdk/emsdk_env.sh
    init: mkdir -p cmbuild && cd cmbuild && emcmake cmake ..
    prebuild: emmake make -j4
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview
# Custom image
image:
  file: .gitpod.Dockerfile
